### ISSUE TITLE
Integrate tiled parser

### ISSUE THREAD

**Issue by Sean-Nishi** [Sean-Nishi/Lunk-Game#20]

**Comment by owalk** [comment]
We will need to check out how the linter looks at the new map format.
For now I won't add any map specific exceptions into the linter

**Comment by owalk** [comment]
The Tiled software has a nice CSV export. We just need a good tileset to use with it first.
After exporting, it will be a CSV of numbers that are mapped to an image out of the tile set.

The draw function for levels will need to hold an enumeration of numbers to images within the tileset. It should be flexible to use with any CSV. All CSV tilesets should use the same width/height in pixels.

**Comment by owalk** [comment]
This should have functional camera logic for the new tile integration
