### ISSUE TITLE
Change repo settings to rebase and merge

### ISSUE THREAD

**Issue by owalk** [Sean-Nishi/Lunk-Game#25]
The current settings allow for merge commits, we should disallow this in favor of rebase and merge on PR close.
There should be a setting to do so under the repository settings.

The image below shows that creating a merge commit is currently the default option. 
Remove the 'create a merge commit' option entirely.

![Image](https://user-images.githubusercontent.com/10580211/217954269-7376a18a-7308-4f0e-a49b-9eb064b13e59.PNG)

**Comment by Sean-Nishi** [comment]
Setting was in my repo settings instead of project settings.
