### ISSUE TITLE
Add 'damsel' object

### ISSUE THREAD

**Issue by owalk** [Sean-Nishi/Lunk-Game#27]
Implement the object to address the following component of the spec sheet:
[Pretty Lady Movement](https://github.com/Sean-Nishi/Lunk-Game/blob/main/docs/specSheet.md#pretty-lady-movement)

**Comment by Sean-Nishi** [comment]
Maybe rename to "damsel", like "damsel in distress"?

**Comment by owalk** [comment]
Damsel would work. It would be funny if some of the "Damsels in distress" were clearly not in any distress and got mad at being saved. We would need to figure something out for that

**Comment by owalk** [comment]
This would need a documentation update and an update to all the related open issues
